CONSUMER_KEY ="tDJCt8CmpWw2gYkQ"
CONSUMER_SECRET = "s3YZEEBaZ3dlCXBnGhGuaBd703gwCQcNSihg6Q6MjFOmg4gGS3"
ACCESS_TOKEN = "NPrTrOUDstDJCt8CmpWw2gYkQ"
ACCESS_TOKEN_SECRET = "s3YZEEBaZ3dlCXBnGhGuaBd703gwCQcNSihg6Q6MjFOmg4gGS3"
